### PR TITLE
fixed getting involved button

### LINKED ISSUE #143: “Getting Involved” Button on Volunteer Page Has No Functionality
## Description

On the https://www.sugarlabs.org/volunteer page, there's a large button labeled “Getting Involved”. However, this button currently has no action associated with it — clicking it does nothing.

Since this page aims to help new users and contributors find ways to participate, having a non-functional button can be confusing and might cause users to drop off.

## How To Reproduce

Clicking the “Getting Involved” button should take the user to a helpful resource, such as:

Sugar Labs GitHub organization (https://github.com/sugarlabs)

A contribution guide

Or a section with volunteer instructions

This will help visitors immediately find a way to participate in the community.

## Screenshots

Image

### Desktop

Operating System: Windows 11

Browser: Chrome

Version: Version 135.0.7049.115 (Official Build) (64-bit)

## Checklist

- [x] I have read and followed the project's Code of Conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided sufficient details to understand and reproduce the issue. I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to help resolve this issue.

---

Thank you for reporting this issue! Your contributions help us improve the project.

📚 **See:** [Contributing Guide](https://github.com/sugarlabs/www-v2/blob/main/docs/CONTRIBUTING.md).

🙋🏾🙋🏼 Need help? Join our [Community Matrix Server](https://matrix.to/#/#sugarlabs-web:matrix.org).

### PR DESCRIPTION
**Pull request by TanmayBansa1**
---
name: fixed getting involved button
about: issue #143 
---

## Description

The getting involved button was not working, so as asked by @sa-fw-an changed it to "get involved" and added scrollIntoView to volunteer cards on click of the button

##After 

https://github.com/user-attachments/assets/1038d655-26d9-43c4-80e8-0b5193c00787

## Related Issue

This PR fixes #143 

## Changes Made

- Changed Getting involved to "Get Involved"
- Added id to volunteer cards section
- Used getElementbyId to scroll onto the volunteer cards section upon click of the button

## Testing Performed

- Tested locally.
- Ran npm run format for the file changed .
- Ran npm run build and npm run lint:ts to verify
- Tested on browsers edge, chrome, arc, brave.
- ...

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [x] I have followed the project's coding style guidelines.
- [x] I have addressed the code review feedback from the previous submission, if applicable.

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/sugarlabs/musicblocks/blob/master/README.md).

🙋🏾🙋🏼 Questions: [Community Matrix Server](https://matrix.to/#/#sugar:matrix.org).

### CODE REVIEW

File: src/pages/Volunteer.tsx [hunk 1]
```diff
@@ -46,8 +46,20 @@ const Volunteer = () => {
...
+              onClick={() => {
+                const gettingInvolvedSection =
+                  document.getElementById('volunteer-cards');
+                if (gettingInvolvedSection) {
+                  gettingInvolvedSection.scrollIntoView({
+                    behavior: 'smooth',
+                    block: 'start',
+                  });
+                }
+              }}
```
Comment (sa-fw-an) [inline src/pages/Volunteer.tsx:60]: It'd better if you could declare this function on top of the file and then call it

Comment (TanmayBansa1) [reply src/pages/Volunteer.tsx]: fixed this in the new commit
