### PR TITLE
Fix/gsoc2025 image rendering 441

### LINKED ISSUE #441: Fix Image Rendering Issue on GSoC 2025 Blog Post
The blog post at https://www.sugarlabs.org/news/all/2025-08-24-gsoc-25-mebinthattil-week12 is experiencing an image rendering issue. The images are not displaying correctly, which is affecting the overall appearance and readability of the post.

### Expected Outcome
The images should be rendered correctly, and the blog post should display as intended.

### Steps to Reproduce
1. Visit the blog post at https://www.sugarlabs.org/news/all/2025-08-24-gsoc-25-mebinthattil-week12
2. Observe the image rendering issue

### Additional Context
This issue should be investigated and resolved to ensure the blog post is displayed correctly and provides a good user experience.

### PR DESCRIPTION
**Pull request by Narendra9793**
---
name: Pull Request
about: Submit changes to the project for review and inclusion
---

## Description

This pull request fixes content and formatting issues in the GSoC 2025 Week 12 blog post by **Mebin J Thattil**.  
The update ensures the post follows the correct structure, frontmatter, and image reference style as instructed by the maintainers.  

## Related Issue

Fixes #441

## Changes Made

- Corrected frontmatter values (title, date, slug, and tags where needed).
- Updated the image URL to use the proper `.webp` format instead of `.png`.
- Fixed formatting inconsistencies in the blog content.
- Aligned the markdown file with project style guidelines.  

## Testing Performed

- Verified that the blog post renders correctly on the development server.
- Confirmed that the updated `.webp` image loads without fallback issues.
- Checked that frontmatter fields (title, date, slug) are parsed correctly.
- Viewed the post in both `NewsPage` and `NewsDetailPage` components to confirm proper rendering.  

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [ ] I have added/updated tests that prove the effectiveness of these changes.
- [ ] I have updated the documentation to reflect these changes, if applicable.
- [x] I have followed the project's coding style guidelines.

## Additional Notes for Reviewers

Please confirm if further cleanup is needed for other GSoC blog posts to maintain consistency across the site.  
This fix applies specifically to the Week 12 post but can serve as a reference for similar corrections.

### CODE REVIEW

File: src/pages/News/NewsDetailPage.tsx [hunk 1]
```diff
@@ -407,6 +407,7 @@ const NewsDetailPage: React.FC = () => {
             />
             <p className="text-white text-center mt-2 text-sm">
               {modalImage.alt}
+              {modalImage.src}
```
Comment (sa-fw-an) [inline src/pages/News/NewsDetailPage.tsx:410]: There is no need to edit this file

File: package-lock.json
Comment (sa-fw-an) [inline package-lock.json:1]: Please remove this file from the commit, we need only the .md file, Package-lock.json is not needed

**Review by sa-fw-an — CHANGES_REQUESTED** [review]
